services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=${MONGO_DB}
    volumes:
      - mongo-data:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: [--auth]

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/${MONGO_DB}?authSource=admin
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  mongo-data:
