name: Build and Push Docker Images

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME_FRONTEND: darkodonev/kiii-frontend
  IMAGE_NAME_BACKEND: darkodonev/kiii-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get and bump version
        id: versioning
        run: |
          VERSION_FILE=".version"
          if [ ! -f "$VERSION_FILE" ]; then
            echo "1.0.0" > $VERSION_FILE
          fi
          VERSION=$(cat $VERSION_FILE)
          IFS='.' read -r major minor patch <<< "$VERSION"
          patch=$((patch + 1))
          NEW_VERSION="$major.$minor.$patch"
          echo $NEW_VERSION > $VERSION_FILE
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push new version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version to ${{ steps.versioning.outputs.version }}"
          file_pattern: .version

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .Dockerfile-frontend
          push: true
          tags: |
            ${{ env.IMAGE_NAME_FRONTEND }}:${{ steps.versioning.outputs.version }}
            ${{ env.IMAGE_NAME_FRONTEND }}:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .Dockerfile-backend
          push: true
          tags: |
            ${{ env.IMAGE_NAME_BACKEND }}:${{ steps.versioning.outputs.version }}
            ${{ env.IMAGE_NAME_BACKEND }}:latest
